language: python
python:  
  - "3.8"

env:
  global:
    - $SECRET_KEY

install:
  - pip install -r requirements.txt

script:
  - python3 manage.py test

# deploy:
#   provider: elasticbeanstalk
#   access_key_id: $ACCESSKEYID
#   secret_access_key: $SECRETACCESSKEY
#   region: "us-west-2"  
#   app: "pipe"
#   env: "pipe-env"
#   bucket_name: "elasticbeanstalk-us-west-2-483486020413"
#   on:
#     branch: master
